### ISSUE TITLE
Edges action parameter missing ?

### ISSUE THREAD

**Issue by matt212** [alexwiench/JSON-Canvas-To-Mermaid#4]
so conventional mermaid  edges has action parameter .
for.e.g:-

```
graph TB
n1[new]-->|usertype submit |n2[awaiting usertype2] 

```
in above case usertype submit is action 
now in JSON canvas to mermaid how above would translate
since there is no way to add action to edge
Kindly provide clarification and guidance on the same 

`	edges: [{ id: 'edge1', fromNode: 'n1', toNode: 'n2',**'actiontext':'usertype submit '** }],`

so is there any mechanism to add actiontext or anything like that .

**Comment by matt212** [comment]
Hi @alexwiench  , 
so while going through src files , I have identified there is field called "label" which can be used to add action to edges 
so it would great if you could add that to the readme documentation 
so it looks like below 

`edges: [{ id: 'edge1', fromNode: 'node1', toNode: 'node2' ,label:'enter action text here'}],`

**Comment by alexwiench** [comment]
Hey @matt212, thanks for looking into this!

Glad you found the `label` property in the JSON Canvas spec. You're right on the money - that's exactly what you need for adding action text to edges.

Just to clarify, this library is for converting existing JSON Canvas to Mermaid, not for building JSON Canvas itself. It is already set up to convert the `label` property to Mermaid syntax, so you're good to go!

Since I'm working with the standard JSON Canvas format, I don't typically document its specifics. But if you think it'd be helpful, I could add a link in the README to the [official JSON Canvas docs](https://jsoncanvas.org/spec/1.0/).

If you are looking for an app to easily create JSON Canvas files, check out [ObsidianMD](https://obsidian.md/). Their canvas allows you to create labels by double clicking on the connecting line. 

![image](https://github.com/user-attachments/assets/f86f1789-4b9f-4349-a36f-5992c2ea489c)


Thanks for your interest in the project. Let me know if you have any other questions!
